runtime: nodejs20
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_instances: 1
  max_instances: 1
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
includes:
  - gcp-envs.yaml
