steps:
- name: 'gcr.io/cloud-builders/docker'
  automapSubstitutions: true
  args: [
    'build',
    '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/registry-api/registryapi:latest',
    '-f', './Dockerfile.prod',
    '.'
  ]
  env:
    - 'DOCKER_BUILDKIT=1'
images: 
    - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/registry-api/registryapi:latest'
options:
  logging: CLOUD_LOGGING_ONLY
