version: "3"

services:
  db:
    build:
      dockerfile: ./pg.Dockerfile
      context: ./sql
    restart: always
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis_db:
    image: redis:7.0.5-bullseye
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass password
    volumes:
      - cache:/data

  app:
    env_file:
      - path: ./.env
    build:
      dockerfile: ./prod.Dockerfile
    hostname: app
    restart: always
    ports:
      - 3030:3030

volumes:
  db:
    driver: local
  cache:
    driver: local

