version: "3"

services:
  db:
    image: postgres
    restart: always
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "default"
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data

  redis_db:
    image: redis:7.0.5-bullseye
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass password
    volumes:
      - cache:/data

  app:
    build:
      dockerfile: ./Dockerfile
    hostname: app
    restart: always
    volumes:
      - .:/home/node/app
      - firebase-cache:/root/.cache/firebase
      - firebase-configs:/root/.config
    ports:
      - 8081:8081 # Cloud Firestore
      - 4001:4001 # Emulator Suite UI
      - 4500:4500 # Logging
      - 4400:4400 # Hub
      - 9229:9229 # Debugger
      - 3000:3000 # Google cloud functions
      - 9150:9150

volumes:
  db:
    driver: local
  cache:
    driver: local
  firebase-cache:
    driver: local
  firebase-configs:
    driver: local
