name: CD - Deploy Docker images

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - name: Docker hub login
        id: docker-hub-login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - uses: docker/build-push-action@v2
        name: Build and push app image
        id: build-and-push-app
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: ${{secrets.DOCKER_APP_IMAGE_TAG}}

      - uses: docker/build-push-action@v2
        name: Build and push SQL image
        id: build-and-push-sql
        with:
          context: "{{defaultContext}}:example"
          file: ./pg.Dockerfile
          push: true
          tags: ${{secrets.DOCKER_SQL_IMAGE_TAG}}
