name: CD - Lint application image in development stage 

on:
  push:
    branches:
      - "feature/**"
      - "perf/**"
      - "refactor/**"
      - "bugfix/**"
      - "ci/**"
      - "chore/**"
      - "release/**"
      - "hotfix/**"
      - "support/**"
      - "dependabot/**"
    paths:
      - "./Dockerhub"
      - "./.github/workflows/lint-dev-app-image.yml"

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - uses: hadolint/hadolint-action@v3.1.0
        id: hadolint
        name: Installing and executing hadolint
        with:
          dockerfile: Dockerfile
