name: CI - Unit & E2E Tests

on:
  push:
    branches: 
      - "*"

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        code: [ 16.x, 18.x, 20.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/actions-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm run test
