name: CI - Tests & Lint

env:
  PROJECT_NAME: ${{secrets.PROJECT_NAME}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  REDIS_URL: ${{secrets.REDIS_URL}}
  COOKIE_KEY: ${{secrets.COOKIE_KEY}}
  HOST_SENDER: ${{secrets.HOST_SENDER}}
  HOST_PORT_SENDER: ${{secrets.HOST_PORT_SENDER}}
  NAME_SENDER: ${{secrets.NAME_SENDER}}
  EMAIL_SENDER: ${{secrets.EMAIL_SENDER}}
  PASS_SENDER: ${{secrets.PASS_SENDER}}
  SIGNATURE_TYPE: ${{secrets.SIGNATURE_TYPE}}

on:
  push:
    branches:
      - "develop"
      - "feature/**"
      - "perf/**"
      - "refactor/**"
      - "bugfix/**"
      - "release/**"
      - "hotfix/**"
      - "support/**"
      - "dependabot/**"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        node: [ 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v3
        id: git-clone
        name: Cloning repository

      - uses: pnpm/action-setup@v2
        id: install-pnpm
        name: Installing PNPM
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        id: set-nodejs
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        id: set-deps
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        id: unit-tests
        run: pnpm run test

  eslint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
        id: git-clone
        name: Cloning repository

      - users: pnpm/action-setup@v2
        id: install-pnpm
        name: Installing PNPM
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        id: set-nodejs
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install dependencies
        id: set-deps
        run: pnpm install --frozen-lockfile

      - name: Run Eslint
        id: eslint
        run: pnpm run lint
